import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Text } from '@chakra-ui/react';


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

        <div className={styles.buttonContainer} >
          <ConnectButton />
        </div>
        
        <div  className={styles.main}>
        <Text
        bgGradient='linear(to-l, #39FF14, #0D7377)'
        bgColor='black'
        bgClip='text'
        fontSize='7xl'
        fontWeight='extrabold'
         >
        Token Airdrop Dpp
        </Text>

        <Text
        bgGradient='linear(to-l, #39FF13, #0D7377)'
        bgColor='black'
        bgClip='text'
        fontSize='xl'
        fontWeight='bold'
         >
        A dapp to airdrop tokens to multiple wallets
        </Text>

        </div>

    </div>

  );
};

export default Home;
